// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PontuacaoRealTime.API.Data;

#nullable disable

namespace PontuacaoRealTime.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("PontuacaoRealTime.API.Models.Consumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataConsumo")
                        .HasColumnType("TEXT");

                    b.Property<int>("PessoaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Consumos");
                });

            modelBuilder.Entity("PontuacaoRealTime.API.Models.Memorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("PontosObtidos")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorPontuavel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsumoId");

                    b.ToTable("Memorial");
                });

            modelBuilder.Entity("PontuacaoRealTime.API.Models.Pontos", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Saldo")
                        .HasColumnType("INTEGER");

                    b.HasKey("PessoaId");

                    b.ToTable("Pontos");
                });

            modelBuilder.Entity("PontuacaoRealTime.API.Models.Memorial", b =>
                {
                    b.HasOne("PontuacaoRealTime.API.Models.Consumo", "Consumo")
                        .WithMany("RegistrosMemorial")
                        .HasForeignKey("ConsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumo");
                });

            modelBuilder.Entity("PontuacaoRealTime.API.Models.Consumo", b =>
                {
                    b.Navigation("RegistrosMemorial");
                });
#pragma warning restore 612, 618
        }
    }
}
